spring:
  servlet:
    multipart:
      max-file-size: 10MB    # Maximum size of an uploaded file
      max-request-size: 10MB # Maximum size of a multipart request
  application:
    name: Task-Management
  datasource:
    url: jdbc:mysql://localhost:3307/work_management_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      static-locations: file:src/main/resources/static/
server:
  port: 8080

